apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30001  # Specify the desired NodePort value
  selector:
    app: mysql

---

apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30002  # Specify the desired NodePort value
  selector:
    app: node

---

apiVersion: v1
kind: Service
metadata:
  name: bankserver-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30003  # Specify the desired NodePort value
  selector:
    app: node
